"""
models/case.py

Case model — the central organizing entity in DFECPIMS.

Case IDs follow the format CASE-YYYY-NNNN:
  - YYYY is the four-digit year the case was opened
  - NNNN is a zero-padded sequence number that resets each year

This means the ID is not auto-generated by Postgres but constructed
at the application layer using CaseSequence (see case_sequence.py).

Status transitions (enforced at the API/service layer, not DB):
  Active → UnderReview → Archived
  Active → Closed
  UnderReview → Active  (reopen)
  UnderReview → Closed

Severity reflects the assessed impact of the incident, not case complexity.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, Enum as SAEnum, DateTime, ForeignKey
from sqlalchemy.orm import relationship

from .base import Base


class CaseSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CaseStatus(str, enum.Enum):
    Active = "Active"
    UnderReview = "UnderReview"
    Archived = "Archived"
    Closed = "Closed"


class Case(Base):
    """
    A forensic investigation case.

    One case can contain many evidence items.
    Every modification to a case should generate an AuditLog entry
    (enforced at the service layer, not DB constraints).
    """

    __tablename__ = "cases"

    id = Column(
        String(20),
        primary_key=True,
        comment="Human-readable case ID in CASE-YYYY-NNNN format",
    )

    title = Column(
        String(500),
        nullable=False,
        comment="Short descriptive title of the case",
    )

    description = Column(
        Text,
        nullable=True,
        comment="Full narrative description of the incident or investigation",
    )

    severity = Column(
        SAEnum(CaseSeverity, name="case_severity", create_type=True),
        nullable=False,
        default=CaseSeverity.MEDIUM,
        comment="Assessed severity of the incident",
    )

    status = Column(
        SAEnum(CaseStatus, name="case_status", create_type=True),
        nullable=False,
        default=CaseStatus.Active,
        comment="Current lifecycle status of the case",
    )

    investigator_id = Column(
        String(36),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="FK to users.id — lead investigator assigned to this case",
    )

    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        comment="UTC timestamp when the case was opened",
    )

    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        # onupdate fires when SQLAlchemy issues an UPDATE for this row.
        # This is sufficient for our needs; we also log changes manually
        # in the audit log for forensic completeness.
        onupdate=lambda: datetime.now(timezone.utc),
        comment="UTC timestamp of the last modification to this case record",
    )

    # --- Relationships ---

    investigator = relationship(
        "User",
        back_populates="cases_assigned",
        foreign_keys=[investigator_id],
        lazy="joined",  # Almost always needed alongside the case record
    )

    evidence_items = relationship(
        "Evidence",
        back_populates="case",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="Evidence.acquired_at",
    )

    audit_logs = relationship(
        "AuditLog",
        back_populates="case",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="AuditLog.timestamp",
    )

    def __repr__(self) -> str:
        return f"<Case id={self.id!r} title={self.title!r} status={self.status!r}>"